[DVX-590] Check for output file existence
DrizlyInc/checks-action pull request #4
Opened 2021-09-13 21:29 UTC by jobimrobinsantos-drizly

Also I updated the README to be more in line with the format we use in Distributor

2021-09-13 21:33 UTC, brettdugan-drizly approved these changes

2021-09-14 13:30 UTC, mikekantzer-drizly requested changes

2021-09-14 13:30 UTC, mikekantzer-drizly commented on README.md
> +    - uses: DrizlyInc/checks-action@main
can we do a versioned release instead of `main`?

2021-09-14 13:31 UTC, jobimrobinsantos-drizly commented on README.md
> +    - uses: DrizlyInc/checks-action@main
Sure, but first we would need to create one

2021-09-14 13:41 UTC, mikekantzer-drizly commented on README.md
> +    - uses: DrizlyInc/checks-action@main
:be the change:

2021-09-14 13:52 UTC, brettdugan-drizly commented
Can we fix the linter?

2021-09-14 15:29 UTC, jobimrobinsantos-drizly commented
I should have never turned on actions for this g.d. repo 😩

2021-09-14 15:45 UTC, jobimrobinsantos-drizly commented
@brettdugan-drizly I am going to politely decline to fix the linting errors, and I'm rewinding some of my changes. The errors were not introduced by my changes, and I'm not a js/ts person (yet) anyhow.

2021-09-14 15:55 UTC, jobimrobinsantos-drizly commented
lol it looks like I stumbled backwards into fixing the linting errors
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi1.wp.com%2Fwww.wehuntedthemammoth.com%2Fwp-content%2Fuploads%2F2016%2F05%2Fpeewee.gif&f=1&nofb=1)

2021-09-15 16:45 UTC, mikekantzer-drizly approved these changes

2021-09-15 16:46 UTC, merged